### ISSUE TITLE
question about runtime correction

### ISSUE THREAD

**Issue by dx118** [jyf588/transformer-inertial-poser#8]
Hi Yifeng,
  I have a question about the root velocity correction and ik correction, since the joints location in world space are determined by both root translation and body pose, and the predictions of root velocity and body pose can't be perfect, then how to decide whether to refine velocity or the body pose so that sbps remain unchanged ?

**Comment by jyf588** [comment]
In the general case when the root is moving (say walking), we only correct the root velocity but keep the predicted body pose unchanged. The reason is that it is usually root velocities that are more inaccurate. The SBPs will not be strictly enforced (i.e. position perfectly unchanged) after this correction, since the root velocity only contains 3 numbers that we can modify. 

You could refer to the "Run-time Root Correction" section in paper, or the code https://github.com/jyf588/transformer-inertial-poser/blob/master/real_time_runner.py#L458 for details.
